[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
[profile.foundry]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test foundry'
[invariant]
fail_on_revert = false